### ISSUE TITLE
Observe Partner's Hand

### ISSUE THREAD

**Issue by hengyuan-hu** [Zamiell/hanabi-live-bot#2]
Thanks for this amazing demo!

I am trying to figure out how to observe the hand of all players. In this example, the hand is constructed as "draw" commands pop in. However, this will return  (-1, -1) for partners cards while return a proper card for my own hand. For example, the following is a print out of a sequence of draws at the beginning of a game (the bot is player 0):

```
player: 0 draw a card: 4/5 at order: 0
player: 0 draw a card: 1/3 at order: 1
player: 0 draw a card: 0/1 at order: 2
player: 0 draw a card: 4/2 at order: 3
player: 0 draw a card: 4/1 at order: 4
player: 1 draw a card: -1/-1 at order: 5
player: 1 draw a card: -1/-1 at order: 6
player: 1 draw a card: -1/-1 at order: 7
player: 1 draw a card: -1/-1 at order: 8
player: 1 draw a card: -1/-1 at order: 9
```

It is fine for the bot to know its own card as we may want to recompute the effect of a hint. However, it is also crucial to know the partner's hand. How to get this feature here?

**Comment by Zamiell** [comment]
> However, this will return (-1, -1) for partners cards while return a proper card for my own hand.

it sounds like you have this backwards. it will return -1, -1 for **your** cards, because in hanabi you cannot see your own hand

**Comment by hengyuan-hu** [comment]
Exactly that's my first thought. But looking at the actual game play, it seems that it indeed tells me about my own card instead of my partners. I the screen shot of game play here.
<img width="584" alt="Screen Shot 2020-05-25 at 12 49 40 PM" src="https://user-images.githubusercontent.com/4728165/82840149-6ffed780-9e86-11ea-955b-50b52f80a2f8.png">

I was trying to play my first card to verify my guess. It turns out that card is indeed a purple 5, i.e. (4/5)

**Comment by hengyuan-hu** [comment]
ah ok. Yeah I forgot that I should change the perspective myself.
