### ISSUE TITLE
Bot not receiving 'yourTurn' signal

### ISSUE THREAD

**Issue by Fruzi** [Zamiell/hanabi-live-bot#3]
Hi,
I'm trying to build a bot to interface with the Hanabi Live server based on this example and am having some issues, even when running the example bot. While it successfully connects to the server and starts the game, it fails to notice that it's their turn and therefor never sends any action so the game is stuck. Is there something that I need to change in the code to get it to do so, or am I not using it correctly?
Thanks in advance.

**Comment by Zamiell** [comment]
its because yourTurn doesn't exist anymore, so the bot has to "manually" look to see what turn it is

see the latest commit

**Comment by Fruzi** [comment]
Unfortunately, the latest commit fails to solve the issue. Firstly, it causes a crash because the class has no "turn" function, but also when fixing that (and a few other places which have to be changed for it to run, handle_action attempts to access dictionary values that have since been changed and no longer exist) it still doesn't notice its turn. If the game assigns the bot as the first player, they never act, otherwise the only act once when force closed and opened mid-game.

**Comment by Zamiell** [comment]
try on master now

**Comment by Fruzi** [comment]
Works great, thank you 👍

**Comment by Zamiell** [comment]
i found some more bugs and fixed them, you should re-pull from master again

**Comment by Fruzi** [comment]
Thanks, only now got around to go back to working on it :)
Do you happen to know if there's a simple way to create bot-bot games? I
want to test my bots in self-play, but currently, they can only play in
games where I human created the room and invited them.
If there's no ready-made solution I'd really appreciate it if you could
clarify how to access a few features of the server I'm fuzzy about so I can
implement this myself.
Ideally, I'd have them join the server, and instead of sending /join I
could send /join {table ID} so that they would create that table if it
doesn't exist and then join it. Once there I'd send /start or something
similar to have them start the game.
In order for that to work, I need to know how to have an agent create a
table, and how to have an agent in a table send a command to start the game.
Thanks in advance anyway,
Uzi

**Comment by Zamiell** [comment]
- open the website like a normal user
- open dev tools
- do things like creating games and joining games and watch what happens in the console. you can see the messages sent and received

if you want the bot to create a table, just copy-paste the function to join a table, and change it accordingly

**Comment by Fruzi** [comment]
Awesome, thanks for the quick response.

**Comment by Fruzi** [comment]
Hi James,
I've got everything set up and working well, except for one issue that I
can't seem to be able to resolve.
After being connected for about 30 minutes, the bot receives an error
message saying "Connection reset by peer" and disconnects.
I'm not sure what's causing it, but it also happened midway through a game
so it's not an issue of the server kicking our AFK players.
Do you have any thoughts on this?
Thanks in advance,
Uzi

**Comment by Zamiell** [comment]
it shouldn't kick afk people.
if you open the site in a browser tab, does it kick you after 30 minutes?
are you using a proxy server?

**Comment by Fruzi** [comment]
I'm connecting to the hanab.live server. When connecting in a browser tab
everything works fine, but the bot gets "Encountered a WebSocket error:
[Errno 104] Connection reset by peer" and quits.

**Comment by Fruzi** [comment]
Fixed, was just an issue with my internet connection :P
