### ISSUE TITLE
gameActionList not working when rejoining the game after disconnect

### ISSUE THREAD

**Issue by hengyuan-hu** [Zamiell/hanabi-live-bot#4]
Previously when the bot rejoins a game, it will receive all the previous actions through gameActionList. This feature seems not working now. The UI also shows the bot as disconnected (red) when it rejoins.

**Comment by Zamiell** [comment]
i dont think the reference bot was intended to handle disconnecting and reconnecting.
dealing with that is left as an exercise to the reader.
remember that there is nothing special about a bot - it just emulates what a real player does.
as a real player, if you refresh the page in the middle of the game, everything will work great - the server sends you the gameActionList, all the cards are redrawn, etc.
thus, the problem sounds like something happening in your code

**Comment by hengyuan-hu** [comment]
Thanks for you reply!

I based my bot on a previous version of this reference bot a year ago and back then the reference bot here can handle connect/disconnect property, i.e. the gameActionList is called when the bot reconnects and I am able to reconstruct whatever the bots need to play from that point. I am trying to rebase the old bot so that it works with the latest version of the hanabi.live server. But somehow the gameActionList no longer works, even for this reference bot without any changes. Is the server not calling the gameActionList upon reconnection or something else changed? I would really appreciate if you can give me some pointers. Thanks!

**Comment by Zamiell** [comment]
i think what changed is that clients are no longer rejoined to a existing games automatically.
clients have to explicitly rejoin the games that they want to rejoin.
(that gives clients more control.)

look at the "welcome" message for the games that you are currently joined to, then reattend them etc.

**Comment by hengyuan-hu** [comment]
Ah, that's exactly what I need. Putting this to the welcome function will do the work.
```python
            for table_id in data["playingAtTables"]:
                print("rejoining table: ", table_id)
                self.send(
                    "tableReattend",
                    {
                        "tableID": table_id,
                    },
                )
```
Thank you so much! Never would have noticed the welcome part by myself.
